### PR TITLE
refactor: else if --> ReplaceKey

### PR DESCRIPTION
**Pull request by zbyti**

### CODE REVIEW

**Comment by Gury8** [comment]
Filename: examples\inpnum.pas
2. 07. 2020 22:27:46
Mad Pascal Compiler version 1.6.4 [2020/06/20] for 6502
Compiling examples\inpnum.pas
examples\inpnum.pas (25,8) Error: Identifier, number or expression expected but 'READLN' found
--------------------------------------------------------------------------------
Filename: examples\locate_gr0.pas
2. 07. 2020 22:27:49
Mad Pascal Compiler version 1.6.4 [2020/06/20] for 6502
Compiling examples\locate_gr0.pas
examples\locate_gr0.pas (27,9) Error: Identifier, number or expression expected but '<' found
--------------------------------------------------------------------------------
Filename: examples\locate_gr7.pas
2. 07. 2020 22:27:50
Mad Pascal Compiler version 1.6.4 [2020/06/20] for 6502
Compiling examples\locate_gr7.pas
examples\locate_gr7.pas (29,9) Error: Identifier, number or expression expected but '<' found
--------------------------------------------------------------------------------
Filename: examples\scompare.pas
2. 07. 2020 22:28:11
Mad Pascal Compiler version 1.6.4 [2020/06/20] for 6502
Compiling examples\scompare.pas
examples\scompare.pas (33,11) Error: Identifier, number or expression expected but '<' found
--------------------------------------------------------------------------------
Filename: examples\stick.pas
2. 07. 2020 22:28:18
Mad Pascal Compiler version 1.6.4 [2020/06/20] for 6502
Compiling examples\stick.pas
examples\stick.pas (20,5) Error: Incompatible types: got "POINTER" expected "BYTE"
--------------------------------------------------------------------------------

**Comment by zbyti** [comment]
OK, I look at it but a brief analysis of this commit make me sure that this change is not responsible for that.

**Comment by zbyti** [comment]
inputnum.pas - yes I make mistake in:

         // ReplaceKey function works on _REPLACMENT array
         temp01 := ReplaceStr(temp01, '<<x>>', ReplaceKey('<<x>>', procName));
         temp02 := ReplaceStr(temp02, '<<x>>', ReplaceKey('<<x>>', procName));
         temp03 := ReplaceStr(temp03, '<<x>>', ReplaceKey('<<x>>', procName));

 I fix it ASAP :]

**Comment by Gury8** [comment]
Don't worry, take a time. Did your heart beat increased on error comment post? :)
I am working on INCLUDE feature, btw.

**Comment by zbyti** [comment]
> Did your heart beat increased on error comment post? :)

A little ;)

**Comment by Gury8** [comment]
Error list was posted with bold and bigger font automatically, not my fault ;)

**Comment by zbyti** [comment]
Problem also is with:

         writeln(temp01);
         writeln(Pos(temp01, 'marker'));
         writeln(temp02);
         writeln(Pos(temp02, 'marker'));
         writeln(temp03);
         writeln(Pos(temp03, 'marker'));

**Comment by zbyti** [comment]
UPS... I used wrong order in POS function :D

**Pull request merged**
